"""Shared inline style definitions for Dash UI layout components."""

STYLES = {
    "input": {
        "width": "100px",
        "borderRadius": "4px",
        "border": "1px solid #ddd",
        "padding": "4px",
    },
    "input_container": {
        "display": "grid",
        "grid-template-columns": "200px 100px 20px",
        "marginBottom": "20px",
        "gap": "20px",
        "align-items": "center",
    },
    "toggle_container": {
        "display": "none",
        "grid-template-columns": "200px 100px 20px",
        "marginTop": "20px",
        "gap": "20px",
        "align-items": "center",
    },
    "reset_button": {
        "padding": "2px 6px",
        "fontSize": "14px",
        "backgroundColor": "#f8f9fa",
        "border": "1px solid #ddd",
        "borderRadius": "4px",
        "cursor": "pointer",
        "height": "25px",
        "width": "30px",
    },
    "header_container": {
        "display": "flex",
        "justifyContent": "space-between",
        "alignItems": "center",
        "marginBottom": "20px",
    },
    "reset_all_button": {
        "padding": "5px 10px",
        "fontSize": "14px",
        "backgroundColor": "#f8f9fa",
        "border": "1px solid #ddd",
        "borderRadius": "4px",
        "cursor": "pointer",
        "height": "30px",
    },
    "input_column": {
        "width": "400px",
        "minWidth": "400px",
        "display": "block",
        "padding": "20px",
        "border": "1px solid black",
        "borderRadius": "8px",
        "boxSizing": "border-box",
        "flex": "0 0 400px",
    },
    "left_column_stack": {
        "width": "400px",
        "minWidth": "400px",
        "display": "flex",
        "flexDirection": "column",
        "gap": "20px",
        "flex": "0 0 400px",
    },
    "plot_box": {
        "width": "100%",
        "display": "block",
        "padding": "20px",
        "border": "1px solid black",
        "borderRadius": "8px",
        "boxSizing": "border-box",
    },
    "plot_column": {
        "width": "auto",
        "minWidth": "0",
        "display": "block",
        "padding": "0px",
        "flex": "1 1 0",
    },
    "container": {
        "display": "flex",
        "alignItems": "flex-start",
        "justifyContent": "flex-start",
        "width": "100%",
        "flexWrap": "nowrap",
        "gap": "20px",
    },
    "export_container": {
        "display": "flex",
        "flexDirection": "column",
        "gap": "8px",
        "marginBottom": "0px",
        "marginLeft": "8px",
    },
    "export_box": {
        "width": "370px",
        "minWidth": "370px",
        "padding": "20px",
        "border": "1px solid black",
        "borderRadius": "8px",
        "backgroundColor": "white",
        "boxSizing": "border-box",
    },
    "export_note_input": {
        "width": "92%",
        "maxWidth": "320px",
        "minHeight": "100px",
        "borderRadius": "4px",
        "border": "1px solid #ddd",
        "padding": "6px",
        "resize": "vertical",
    },
    "export_button": {
        "padding": "6px 12px",
        "fontSize": "14px",
        "backgroundColor": "#f8f9fa",
        "border": "1px solid #ddd",
        "borderRadius": "4px",
        "cursor": "pointer",
        "height": "34px",
        "width": "150px",
    },
    "export_status": {
        "minHeight": "0px",
        "fontSize": "12px",
        "color": "#333",
    },
}
