# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest pytest-cov coveralls
    - name: Install openairbearing in editable mode
      run: pip install -e .
    - name: Lint with Ruff
      run: |
        ruff check .
        ruff format --check .
    - name: Test with pytest
      run: |
        pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=openairbearing --cov-report=xml --cov-report=html --cov-report=term
    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls